"""add phone number

Revision ID: 64596b7e2429
Revises: 6a9dc484b079
Create Date: 2022-06-28 09:12:37.301541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64596b7e2429'
down_revision = '6a9dc484b079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
